# Generated by Django 2.1.7 on 2019-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_company',
            name='image',
            field=models.ImageField(upload_to='myimages/'),
        ),
    ]
