# Generated by Django 2.1.7 on 2019-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190305_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Agent',
            fields=[
                ('id', models.IntegerField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='add_company',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
