# Generated by Django 2.1.7 on 2019-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190310_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_company',
            name='id',
        ),
        migrations.AlterField(
            model_name='add_company',
            name='email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
