# Generated by Django 2.1.7 on 2019-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_agent_add_company_companyreg_customer_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_agent',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_company',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
