# Generated by Django 2.1.7 on 2019-03-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190317_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares_Add',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=1)),
                ('price', models.IntegerField()),
                ('select', models.CharField(max_length=30)),
            ],
        ),
    ]
