# Generated by Django 2.1.7 on 2019-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_shares_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
