# Generated by Django 2.1.7 on 2019-03-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggesstion',
            fields=[
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('suggession', models.CharField(max_length=100)),
            ],
        ),
    ]
