# Generated by Django 2.1.7 on 2019-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_suggesstion'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares_add',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
